# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[git]
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->Performance" },
  { message = "^doc", group = "<!-- 3 -->Documentation" },
  { message = "^refactor", group = "<!-- 4 -->Refactor" },
  { message = "^style", group = "<!-- 5 -->Styling" },
  { message = "^test", group = "<!-- 6 -->Testing" },
  { message = "^chore", group = "<!-- 7 -->Chore" },
  { message = "^ci", group = "<!-- 8 -->CI" },
]
# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
