[workspace]
semver_check = true
allow_dirty = true
changelog_config = "cliff.toml"

[[package]]
name = "oxc-miette"
version_group = "group"
changelog_include = ["oxc-miette-derive"]

[[package]]
name = "oxc-miette-derive"
version_group = "group"
changelog_update = false
